title: Eric Moore
subtitle: 学海无涯，共同进步！
language: zh-CN
timezone: Asia/Shanghai

url: https://eric-gitta-moore.github.io
permalink: :title/

archive_generator:
  per_page: 25

theme: maupassant

public_dir: ../public
post_asset_folder: true